### ISSUE TITLE
headless flag prevents code from running

### ISSUE THREAD

**Issue by cood1n** [Sxvxgee/UnlimitedGPT#1]
this is the code i currently have:
```py
import os
from UnlimitedGPT import ChatGPT

def cls():
    os.system("cls" if os.name == "nt" else "clear")
cls()

session_token = input("Enter your session token:\nThis data will be stored locally for convenience.\n> ")
cls()
cnv = input("Enter your conversation ID:\nYou can obtain this by opening a conversation on the ChatGPT client and copying everything after the /c/ in the URL.\n> ")
cls()
msg = input("Enter message:\n> ")
cls()

api = ChatGPT(
    session_token,
    proxy=None,
    disable_moderation=True,
    conversation_id=cnv,
    verbose=True,
    input_mode="SLOW",
    input_delay=0.2,
    headless="True"
)

api.clear_conversations()
message = api.send_message(msg)
print(message.response)
```

whenever ran, it initializing the browser then throws this error:
```
[_init_browser] Initializing browser...
Traceback (most recent call last):
  File "C:\Users\Noah Coodin\Downloads\coodingpt\main.py", line 15, in <module>
    api = ChatGPT(
          ^^^^^^^^
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\UnlimitedGPT\UnlimitedGPT.py", line 77, in __init__
    self._init_browser()
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\UnlimitedGPT\UnlimitedGPT.py", line 158, in _init_browser
    raise e
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\UnlimitedGPT\UnlimitedGPT.py", line 154, in _init_browser
    self.driver = ChatGPTDriver(options=options, headless=self._headless)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\UnlimitedGPT\internal\driver.py", line 11, in __init__
    super().__init__(options=options, headless=headless)
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 386, in __init__
    if self.patcher.version_main < 108:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
im on python 3.11.3
```

**Comment by Sxvxgee** [comment]
Thanks for reporting the issue, I'll look into it in a few minutes and get back to you. At the meantime, could you answer the following questions?

1. What OS are you on?
2. Are you running the latest version of UnlimitedGPT?
3. Does the code work when headless mode is not set to True?

**Comment by cood1n** [comment]
Also I'm now realizing in the code provided I have true in quotes, but I tried no quotes and the same error occurred.

**Comment by cood1n** [comment]
Log of trying to use with a valid conversation ID:
```
[_init_browser] Initializing browser...
[_init_browser] Restoring session_token...
[_init_browser] Blocking moderation...
[_init_browser] Ensuring Cloudflare cookies...
[_ensure_cf] Opening new tab...
[_ensure_cf] Getting Cloudflare challenge...
[_ensure_cf] Cloudflare challenge passed
[_ensure_cf] Validating authorization...
[_ensure_cf] Authorization is valid
[_ensure_cf] Closing tab...
[_init_browser] Opening chat page...
[_check_blocking_elements] Looking for blocking elements...
[_keep_alive] Updating session...
[clear_conversations] Clearing all conversations...
Traceback (most recent call last):
  File "C:\Users\Noah Coodin\Downloads\coodingpt\main.py", line 25, in <module>
    api.clear_conversations()
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\UnlimitedGPT\UnlimitedGPT.py", line 383, in clear_conversations
    clear_conversations.click() # Confirm button is the same path
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 403, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=114.0.5735.91)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00CE8893+48451]
        (No symbol) [0x00C7B8A1]
        (No symbol) [0x00B85058]
        (No symbol) [0x00B883F1]
        (No symbol) [0x00B89631]
        (No symbol) [0x00B896D0]
        (No symbol) [0x00BB1879]
        (No symbol) [0x00BA98FD]
        (No symbol) [0x00BCA2BC]
        (No symbol) [0x00BA9586]
        (No symbol) [0x00BCA614]
        (No symbol) [0x00BDC482]
        (No symbol) [0x00BCA0B6]
        (No symbol) [0x00BA7E08]
        (No symbol) [0x00BA8F2D]
        GetHandleVerifier [0x00F48E3A+2540266]
        GetHandleVerifier [0x00F88959+2801161]
        GetHandleVerifier [0x00F8295C+2776588]
        GetHandleVerifier [0x00D72280+612144]
        (No symbol) [0x00C84F6C]
        (No symbol) [0x00C811D8]
        (No symbol) [0x00C812BB]
        (No symbol) [0x00C74857]
        BaseThreadInitThunk [0x75F100C9+25]
        RtlGetAppContainerNamedObjectPath [0x77047B4E+286]
        RtlGetAppContainerNamedObjectPath [0x77047B1E+238]

[__del__] Closing browser...
```

**Comment by Sxvxgee** [comment]
Yeah I just noticed the headless mode in your code having the value set as `str`, but I'm currently downloading a new version of chrome as apparently mine is not supported anymore by the newest `undetected-chromedriver` library. Once the installation is done I'll look into the bug and try to fix it.

**Comment by Sxvxgee** [comment]
> Log of trying to use with a valid conversation ID:
> 
> ```
> [_init_browser] Initializing browser...
> [_init_browser] Restoring session_token...
> [_init_browser] Blocking moderation...
> [_init_browser] Ensuring Cloudflare cookies...
> [_ensure_cf] Opening new tab...
> [_ensure_cf] Getting Cloudflare challenge...
> [_ensure_cf] Cloudflare challenge passed
> [_ensure_cf] Validating authorization...
> [_ensure_cf] Authorization is valid
> [_ensure_cf] Closing tab...
> [_init_browser] Opening chat page...
> [_check_blocking_elements] Looking for blocking elements...
> [_keep_alive] Updating session...
> [clear_conversations] Clearing all conversations...
> Traceback (most recent call last):
>   File "C:\Users\Noah Coodin\Downloads\coodingpt\main.py", line 25, in <module>
>     api.clear_conversations()
>   File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\UnlimitedGPT\UnlimitedGPT.py", line 383, in clear_conversations
>     clear_conversations.click() # Confirm button is the same path
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
>     self._execute(Command.CLICK_ELEMENT)
>   File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 403, in _execute
>     return self._parent.execute(command, params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
>   (Session info: chrome=114.0.5735.91)
> Stacktrace:
> Backtrace:
>         GetHandleVerifier [0x00CE8893+48451]
>         (No symbol) [0x00C7B8A1]
>         (No symbol) [0x00B85058]
>         (No symbol) [0x00B883F1]
>         (No symbol) [0x00B89631]
>         (No symbol) [0x00B896D0]
>         (No symbol) [0x00BB1879]
>         (No symbol) [0x00BA98FD]
>         (No symbol) [0x00BCA2BC]
>         (No symbol) [0x00BA9586]
>         (No symbol) [0x00BCA614]
>         (No symbol) [0x00BDC482]
>         (No symbol) [0x00BCA0B6]
>         (No symbol) [0x00BA7E08]
>         (No symbol) [0x00BA8F2D]
>         GetHandleVerifier [0x00F48E3A+2540266]
>         GetHandleVerifier [0x00F88959+2801161]
>         GetHandleVerifier [0x00F8295C+2776588]
>         GetHandleVerifier [0x00D72280+612144]
>         (No symbol) [0x00C84F6C]
>         (No symbol) [0x00C811D8]
>         (No symbol) [0x00C812BB]
>         (No symbol) [0x00C74857]
>         BaseThreadInitThunk [0x75F100C9+25]
>         RtlGetAppContainerNamedObjectPath [0x77047B4E+286]
>         RtlGetAppContainerNamedObjectPath [0x77047B1E+238]
> 
> [__del__] Closing browser...
> ```

Could you try again but with headless mode set to False?

**Comment by Sxvxgee** [comment]
Alright so this error should be fairly simple to fix. It is being raised because the code is trying to click the elements without checking if they are "clickable". I can add a check before clicking which should fix it. I'll work on that now.

**Comment by cood1n** [comment]
Not near my computer at the moment, I’ll get back to you once I’m back
home. If you could please reply to this issue if you push an update that’d
be greatly appreciated.

**Comment by Sxvxgee** [comment]
I'm currently fixing the bug, once the update is pushed I'll make sure to let you know.

**Comment by Sxvxgee** [comment]
I believe the issue has been fixed now. Please do let me know once you test your code once again after updating the library.

You can update the library using the following command:
```sh
pip install UnlimitedGPT -U
```

**Comment by cood1n** [comment]
It's launching chrome and authenticating successfully, but hangs when sending the message on both SLOW and FAST mode for me.

This is what it says after timing out while waiting for the message to send:
```
[_init_browser] Initializing browser...
[_init_browser] Initializing browser...
[_init_browser] Restoring session_token...
[_init_browser] Blocking moderation...        
[_init_browser] Ensuring Cloudflare cookies...
[_ensure_cf] Opening new tab...
[_ensure_cf] Getting Cloudflare challenge...
[_ensure_cf] Cloudflare challenge passed
[_ensure_cf] Validating authorization...
[_ensure_cf] Authorization is valid
[_ensure_cf] Closing tab...
[_init_browser] Opening chat page...
[_check_blocking_elements] Looking for blocking elements...
[_keep_alive] Updating session...
[send_message] Sending message with mode SLOW with 0.2 delay...
[_keep_alive] Updating session...
Traceback (most recent call last):
  File "C:\Users\Noah Coodin\Downloads\coodingpt\main.py", line 26, in <module>
    message = api.send_message(msg)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\UnlimitedGPT\UnlimitedGPT.py", line 304, in send_message
    textbox = WebDriverWait(self.driver, 60).until(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00248893+48451]
        (No symbol) [0x001DB8A1]
        (No symbol) [0x000E5058]
        (No symbol) [0x00110467]
        (No symbol) [0x0011069B]
        (No symbol) [0x0013DD92]
        (No symbol) [0x0012A304]
        (No symbol) [0x0013C482]
        (No symbol) [0x0012A0B6]
        (No symbol) [0x00107E08]
        (No symbol) [0x00108F2D]
        GetHandleVerifier [0x004A8E3A+2540266]
        GetHandleVerifier [0x004E8959+2801161]
        GetHandleVerifier [0x004E295C+2776588]
        GetHandleVerifier [0x002D2280+612144]
        (No symbol) [0x001E4F6C]
        (No symbol) [0x001E11D8]
        (No symbol) [0x001E12BB]
        (No symbol) [0x001D4857]
        BaseThreadInitThunk [0x75F100C9+25]
        RtlGetAppContainerNamedObjectPath [0x77047B4E+286]
        RtlGetAppContainerNamedObjectPath [0x77047B1E+238]
        (No symbol) [0x00000000]

[__del__] Closing browser...
```
PS: I used no conversation ID for this, I will now try using one and reply to this with results.

**Comment by Sxvxgee** [comment]
Could you show me your code? Also did you update the library?

**Comment by cood1n** [comment]
Update: It works flawlessly when provided a conversation ID, however if the variable is left blank or never specified it will just hang while waiting to send the message.

Yes, I updated the library. I am now on version 0.1.1.

Here is my code:
```py
import os
from UnlimitedGPT import ChatGPT

def cls():
    os.system("cls" if os.name == "nt" else "clear")
cls()

session_token = input("Enter your session token:\nThis data will be stored locally for convenience.\n> ")
cls()
cnv = input("Enter your conversation ID:\nYou can obtain this by opening a conversation on the ChatGPT client and copying everything after the /c/ in the URL.\n> ")
cls()
msg = input("Enter message:\n> ")
cls()

api = ChatGPT(
    session_token,
    proxy=None,
    disable_moderation=True,
    conversation_id=cnv,
    headless=False,
    verbose=True,
    input_mode="SLOW",
    input_delay=0.2,
)

message = api.send_message(msg)
print(message.response)
```

**Comment by Sxvxgee** [comment]
I've just realized the majority of functions no longer work because OpenAI released a new update to the ChatGPT website. I'm currently working on a release that will fix them all.

**Comment by cood1n** [comment]
Working close tonight, I’ll let you know later into the evening.

**Comment by cood1n** [comment]
Headless still appears to be broken, when set to true it throws this error:
```
[_init_browser] Initializing browser...
Traceback (most recent call last):
  File "C:\Users\Noah Coodin\Downloads\coodingpt\main.py", line 15, in <module> 
    api = ChatGPT(
          ^^^^^^^^
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\UnlimitedGPT\UnlimitedGPT.py", line 72, in __init__
    self._init_browser()
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\UnlimitedGPT\UnlimitedGPT.py", line 153, in _init_browser
    raise e
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\UnlimitedGPT\UnlimitedGPT.py", line 149, in _init_browser
    self.driver = ChatGPTDriver(options=options, headless=self._headless)       
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\UnlimitedGPT\internal\driver.py", line 11, in __init__
    super().__init__(options=options, headless=headless)
  File "C:\Users\Noah Coodin\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 386, in __init__
    if self.patcher.version_main < 108:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
using this code:
```py
import os
from UnlimitedGPT import ChatGPT

def cls():
    os.system("cls" if os.name == "nt" else "clear")
cls()

session_token = input("Enter your session token:\nThis data will be stored locally for convenience.\n> ")
cls()
cnv = input("Enter your conversation ID:\nYou can obtain this by opening a conversation on the ChatGPT client and copying everything after the /c/ in the URL.\n> ")
cls()
msg = input("Enter message:\n> ")
cls()

api = ChatGPT(
    session_token,
    proxy=None,
    disable_moderation=True,
    conversation_id=cnv,
    headless=True,
    verbose=True
)
api.get_session_data()
message = api.send_message(msg)
print(message.response)
```

Also whatever you're passing the conversation_id variable is missing the c in between the two slashes. Currently, it attempts to go to https://chat.openai.com//conversation_id, when there should be a c in between the 2 last slashes.

**Comment by Sxvxgee** [comment]
Have you updated the library? If you did and you still got that issue with headless mode, then I suggest making an issue on the [undetected-chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) repository as headless mode works for me, and it has been pointed out some users were facing issues with it based on the OS they're using the library on.

As for the issue with the conversation ID, I'm currently working on the fix and I'll push it soon.

**Comment by Sxvxgee** [comment]
Version `0.1.2.5` is now released. Update the library then try your code and let me know if it works. If you still face the same issue with headless mode, it's not because of this library and you need to open an issue at the repository of `undetected-chromedriver`.

**Comment by Sxvxgee** [comment]
Closing the issue as there has been no reply.
