### ISSUE TITLE
[bug] Change in button for new chat when chat history is off

### ISSUE THREAD

**Issue by GitPeterJ** [Sxvxgee/UnlimitedGPT#13]
### Description
For my use case, a new chat is started when it's done with the current item. Since keeping the history is not important I decides to turn it off to prevent my history from being flooded (and it also prevents your data from being analyzed by OpenAI). The only problem is that the text for a new chat changed from `New chat` to `Clear chat`.

### Steps to Reproduce

Turn off chat history and call `reset_conversation()`, this will take some time because of the timeout after which it will continue still in the same chat.

### Expected Behavior

Chat becoming empty.

### Possible Solutions

I already modified the text in chatgpt_data.py, but for a proper solution and to make it easier for others I propose to:
Add an instance variable in which the state of the chat history is set (defaults to True), since the option is reset each time a new instance is called and needs to be updated in toggle_chat_history. Finally based on the state of chat history decide if `New chat` or `Clear chat` needs to be used.

### Checklist

Before submitting the issue, please ensure that you have done the following:

- [ ] Keep chat_history toggle in the object.
- [ ] Decide based on chat_history if `New chat` or `Clear chat` needs to be used.

**Comment by Sxvxgee** [comment]
Hello, thanks so much for the bug report! I'll fix it now. Also I'd like you for following the template and submitting a very helpful description of the issue and also on the other categories too! I'll check it out soon and I'll make a fix to it - I'll most likely use the solution you've suggested, as it sounds pretty good.

**Comment by Sxvxgee** [comment]
It may take a while for a new version to be released with the fix for this issue, as I'm currently working on a huge update that should be released soon, which will include the fix for this bug.

**Comment by GitPeterJ** [comment]
No problem, I know the frustration of when an issue does not have the required information to debug it. Great that it's already implemented!
