### ISSUE TITLE
[BUG] Fail to get conversation id

### ISSUE THREAD

**Issue by a-huk** [Sxvxgee/UnlimitedGPT#16]
### Description
I am running a simple example: see code section
I see the chromium window open, ask the question, even the answer is output, but then it fails while trying to get the conversation id as it does not find any log performance.

### Steps to Reproduce

Please provide clear steps to reproduce the issue you're facing.

### Code used
```python
from UnlimitedGPT import ChatGPT

session_token = 'XXX'
api = ChatGPT(session_token)  # auth with session token
resp = api.send_message('Hello, world!')
print(message.response, message.conversation.id)
```

### Error Message or Traceback

`Traceback (most recent call last):
  File "/home/hukad/Downloads/pyChatGPT/../test_ai.py", line 5, in <module>
    resp = api.send_message('Hello, world!')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hukad/venv/lib/python3.11/site-packages/UnlimitedGPT/UnlimitedGPT.py", line 634, in send_message
    self._get_conversation_id()
  File "/home/hukad/venv/lib/python3.11/site-packages/UnlimitedGPT/UnlimitedGPT.py", line 351, in _get_conversation_id
    logs_raw = self.driver.get_log("performance")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hukad/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 1027, in get_log
    return self.execute(Command.GET_LOG, {"type": log_type})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hukad/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/hukad/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: log type 'performance' not found
  (Session info: chrome=114.0.5735.133)
Stacktrace:
#0 0x559af30db4e3 <unknown>
#1 0x559af2e0ac76 <unknown>
#2 0x559af2e74b69 <unknown>
#3 0x559af2e65fd8 <unknown>
#4 0x559af2e3b2dd <unknown>
#5 0x559af2e3c34e <unknown>
#6 0x559af309b3e4 <unknown>
#7 0x559af309f3d7 <unknown>
#8 0x559af30a9b20 <unknown>
#9 0x559af30a0023 <unknown>
#10 0x559af306e1aa <unknown>
#11 0x559af30c46b8 <unknown>
#12 0x559af30c4847 <unknown>
#13 0x559af30d4243 <unknown>
#14 0x7f04662dcfd4 <unknown>`

### Environment Information

Please provide details about your environment:

- Python version: 3.11.2
- Operating System: Ubuntu 2022
- UnlimitedGPT version: Latest

### Expected Behavior

Correct output

**Comment by Sxvxgee** [comment]
Hi, this bug can be fixed by installing the correct version of the dependencies.

Run the following commands: 
```
pip uninstall undetected-chromedriver -y
pip uninstall selenium -y
pip install undetected-chromedriver==3.4.5
pip install selenium==4.9.1
```

Next version will have the correct versions specified. Let me know if this fixes your issue.
