### ISSUE TITLE
install_chromedriver() error 

### ISSUE THREAD

**Issue by newbiecoderrrrrr** [Sxvxgee/UnlimitedGPT#17]
I followed your manual.
I ran the code on Colab.

# install dependencies
!apt install chromium-browser xvfb
!pip install -U selenium_profiles UnlimitedGPT
It has been executed successfully up to this point.

However, an error occurs at this point.
from selenium_profiles.utils.installer import install_chromedriver
install_chromedriver()

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-2-d1c54d490ddb>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from selenium_profiles.utils.installer import install_chromedriver
      2 install_chromedriver()

ImportError: cannot import name 'install_chromedriver' from 'selenium_profiles.utils.installer' (/usr/local/lib/python3.10/dist-packages/selenium_profiles/utils/installer.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

So, according to the error message, when I searched for this 'selenium_profiles/utils/installer.py',
 'install_chromedriver' was not found.

Please provide a solution to resolve the erro

**Comment by Sxvxgee** [comment]
Hi, I'm currently busy with a few things IRL. I'll have a look and get back to you soon.

**Comment by Sxvxgee** [comment]
Well, I don't know how to fix this issue. I guess you'll have to do some googling. I'll remove the whole google collab thing from my README so there wouldn't be any confusion.
