### ISSUE TITLE
Reduce loading time

### ISSUE THREAD

**Issue by PushkarOP** [Sxvxgee/UnlimitedGPT#22]
It takes 4-5 minutes to load the code on linux. If possible make it fast otherwise no problem

**Comment by mpetruc** [comment]
3'14" on windows. Not a complaint, just an observation. Suggestion: would be useful to have a progress bar to give an indication that it's actually doing something and may be how long it's gonna take. Otherwise, thank you for your work and for sharing

**Comment by Sxvxgee** [comment]
Fixed in the new version, update to `0.1.8` by running `python3 -m pip install UnlimitedGPT -U` or `pip install UnlimitedGPT -U` and try your code again then let me know if you still face this issue - you shouldn't face it anymore though.
