### ISSUE TITLE
[BUG] Not progress after popup "This is a free research preview"

### ISSUE THREAD

**Issue by jaewoo-so** [Sxvxgee/UnlimitedGPT#24]
> Make sure to start your title with the prefix "[BUG]" followed by a title that describes the bug you're facing within a few words

### Description
 Not progress after popup "This is a free research preview". just hang forever. 

### Error Message or Traceback
![image](https://github.com/Sxvxgee/UnlimitedGPT/assets/36718545/a65a8f17-9825-4ee4-a503-7662dac2cc2a)

If applicable, include the complete error message or traceback you received. This will help us in identifying the problem more quickly.

```python
Paste the error message or traceback here.
```

### Environment Information

Please provide details about your environment:

- Python version: 3.8
- Operating System: windows
- UnlimitedGPT version: 0.1.7

### Expected Behavior

Describe what you expected to happen when encountering the issue.

### Possible Solutions

If you have any ideas or suggestions for resolving the issue, please mention them here.

### Additional Context

Provide any additional information or context that may be helpful in understanding and resolving the issue. This can include:

- Any modifications made to the library or code.
- Any related information about the system or environment.
- Screenshots, if applicable, to visually illustrate the issue.

### Checklist

Before submitting the issue, please ensure that you have done the following:

- [ ] I have reviewed the documentation before submitting this but report.
- [ ] I have confirmed that I am running the latest version of UnlimitedGPT.
- [ ] I have verified that the issue is not caused by any modifications you made to the library or code.
- [ ] I have confirmed that the issue is caused by the library itself and not other dependencies used. [E.G headless mode not working because of undetected-chromedriver]

Thank you for taking the time to report this issue. Your contribution helps improve UnlimitedGPT for everyone!

**Comment by BainBan** [comment]
same issue

**Comment by Sxvxgee** [comment]
Thank you for reporting this issue. I'll be releasing a new version soon with a fix to this problem.

**Comment by mukund1606** [comment]
Can I work on this issue and open PR?

**Comment by Sxvxgee** [comment]
Fixed in the new version, update to `0.1.8` by running `python3 -m pip install UnlimitedGPT -U` or `pip install UnlimitedGPT -U` and try your code again then let me know if you still face this issue - you shouldn't face it anymore though.

**Comment by Sxvxgee** [comment]
> Can I work on this issue and open PR?

Always feel free to make a PR. However now this issue has been fixed in the new update.

**Comment by mukund1606** [comment]
👍
