### ISSUE TITLE
[BUG] self._chrome_args is nonetype (not iterable)

### ISSUE THREAD

**Issue by maxPrakken** [Sxvxgee/UnlimitedGPT#26]
I made a python file and put in the initialization code from the README :
```
from UnlimitedGPT import ChatGPT


session_token = "MYTOKEN"
conversation_id = "YOUR_CONVERSATION_ID"

chatbot = ChatGPT(
    session_token, 
    conversation_id=None,
    proxy=None,
    chrome_args=None,
    disable_moderation=False,
    verbose=False,
)

```
when i compile this is spits out that `_chrome_args` is not iterable. This happends on line 155 of `UnlimitedGPT.py` in the `_init_browser(self)` function

**Comment by Laranjo1** [comment]
add --headless

**Comment by Sxvxgee** [comment]
`chrome_args` cannot be None or anything besides a list. It can be an empty list if you want though.
