### ISSUE TITLE
ModuleNotFoundError: No module named 'UnlimitedGPT.internal'

### ISSUE THREAD

**Issue by AlexLuya** [Sxvxgee/UnlimitedGPT#28]
### Environment Information

Please provide details about your environment:

- Python version: 3.10
- Operating System: ubuntu 22.04
- UnlimitedGPT version: main

Below code
```
from UnlimitedGPT import ChatGPT 
api = ChatGPT("token") 
api._proxy = "http://127.0.0.1:20171"
message = api.send_message("Hello ChatGPT!")  
new_message = api.regenerate_response()  
data = api.get_session_data()  
api.toggle_chat_history(False) 
```

Report:
```
Traceback (most recent call last):
  File "/home/alex/workspace/gRPC-Test/web/py/chatgpt.py", line 27, in <module>
    from UnlimitedGPT import ChatGPT 
  File "/usr/local/lib/python3.10/dist-packages/UnlimitedGPT-0.1.7-py3.10.egg/UnlimitedGPT/__init__.py", line 7, in <module>
ModuleNotFoundError: No module named 'UnlimitedGPT.internal'
```

**Comment by Sxvxgee** [comment]
Interesting.. I'll have to test it and get back to you soon, haven't seen this problem occur before. In the mean time, can you try uninstalling and reinstalling the library?

**Comment by Sxvxgee** [comment]
Fixed in the new version, update to `0.1.8` by running `python3 -m pip install UnlimitedGPT -U` or `pip install UnlimitedGPT -U` and try your code again then let me know if you still face this issue - you shouldn't face it anymore though.

**Comment by desis123** [comment]
I am having the same issue, Even with pip install UnlimitedGPT -U  . I have checked with python 3.9 and 3.11 . both having the same issue .

**Comment by desis123** [comment]
Okay I have somewhat figure out what's going on. But I have solved it manually but dont know how to solve it pragmatically . Actually pip install is not downloading the full code .. specially not internal folder .. so I have download zip from github and manually copy that folder in site-packages folder to solve that issue

**Comment by Sxvxgee** [comment]
Version `0.1.8.5` is now out with the fix for this issue, please update and let me know if you face any further problems
