### ISSUE TITLE
Can't send any message

### ISSUE THREAD

**Issue by flolep2607** [Sxvxgee/UnlimitedGPT#4]
I think they just changed their design, so you don't have the good selector now

**Comment by Sxvxgee** [comment]
Can you show me your code and traceback? I'll check now too

**Comment by Sxvxgee** [comment]
Version `0.1.3` is out. Update the library by running the following command:
```
pip install UnlimitedGPT -U
```

This updated adds a new function and fixes the outdated selectors. Please update the library on your machine and let me know if the issue is fixed.

**Comment by flinkfactory** [comment]
Came here to look for a solution and just tried the new version. That fixed it for me, thanks a lot @Sxvxgee !

**Comment by Sxvxgee** [comment]
> Came here to look for a solution and just tried the new version. That fixed it for me, thanks a lot @Sxvxgee !

Glad to hear that! Please consider starring the project if you like it and haven't already, it'd mean the world :)

**Comment by Sxvxgee** [comment]
Closing the issue as the bug has been fixed.
