### ISSUE TITLE
Shows invalid session token

### ISSUE THREAD

**Issue by AtiUsm** [Sxvxgee/UnlimitedGPT#53]
> Make sure to start your title with the prefix "[BUG]" followed by a title that describes the bug you're facing within a few words

### Description
I am following the instructions 100 percent getting the right token still says invalid session token
### Steps to Reproduce

Please provide clear steps to reproduce the issue you're facing.

### Code used
Please provide the code that you were using when you encountered the bug.

```python
Paste the relevant code here.
```

### Error Message or Traceback

If applicable, include the complete error message or traceback you received. This will help us in identifying the problem more quickly.

```python
Paste the error message or traceback here.
```

### Environment Information

Please provide details about your environment:

- Python version: 
- Operating System: 
- UnlimitedGPT version: 

### Expected Behavior

Describe what you expected to happen when encountering the issue.

### Possible Solutions

If you have any ideas or suggestions for resolving the issue, please mention them here.

### Additional Context

Provide any additional information or context that may be helpful in understanding and resolving the issue. This can include:

- Any modifications made to the library or code.
- Any related information about the system or environment.
- Screenshots, if applicable, to visually illustrate the issue.

### Checklist

Before submitting the issue, please ensure that you have done the following:

- [ ] I have reviewed the documentation before submitting this but report.
- [ ] I have confirmed that I am running the latest version of UnlimitedGPT.
- [ ] I have verified that the issue is not caused by any modifications you made to the library or code.
- [ ] I have confirmed that the issue is caused by the library itself and not other dependencies used. [E.G headless mode not working because of undetected-chromedriver]

Thank you for taking the time to report this issue. Your contribution helps improve UnlimitedGPT for everyone!

**Comment by AtiUsm** [comment]
![Screenshot (59)](https://github.com/user-attachments/assets/8f116dbb-a5a3-4a5d-a830-e0ba4f435ec8)

**Comment by AtiUsm** [comment]
![Screenshot (54)](https://github.com/user-attachments/assets/1d930256-792f-4a38-b941-f77146d5a789)

**Comment by AtiUsm** [comment]
![Screenshot (60)](https://github.com/user-attachments/assets/442b7f40-343c-4860-8dd4-b1dd265b615b)

**Comment by AtiUsm** [comment]
![Screenshot (61)](https://github.com/user-attachments/assets/73f9c7f6-d4e0-4c39-bbe8-724625e28cfe)

**Comment by AtiUsm** [comment]
![Screenshot (62)](https://github.com/user-attachments/assets/7b9e6569-63c7-4542-a208-b9f587c4ead7)
cODE OPENS THE CHROME BROWSER BUT SHOWS INVALID SESSION TOKEN (all photos provided)

**Comment by AtiUsm** [comment]
![Screenshot (62)](https://github.com/user-attachments/assets/d321976a-3e1e-48ea-add8-93c159d738df)
Code opens the chrome browser but shows invalid session tokjen

**Comment by dsldsl** [comment]
@AtiUsm did you solve this?
