### ISSUE TITLE
headless = True error

### ISSUE THREAD

**Issue by awais-tolu** [Sxvxgee/UnlimitedGPT#7]
> Make sure to start your title with the prefix "[BUG]" followed by a title that describes the bug you're facing within a few words

### Description
Provide a detailed description of the bug you are facing, this will make understanding the issue and finding a solution for it easier.

### Steps to Reproduce

Please provide clear steps to reproduce the issue you're facing.

### Code used
Please provide the code that you were using when you encountered the bug.

```python
Paste the relevant code here.
```

### Error Message or Traceback

If applicable, include the complete error message or traceback you received. This will help us in identifying the problem more quickly.

```python
Paste the error message or traceback here.
```

### Environment Information

Please provide details about your environment:

- Python version: 
- Operating System: 
- UnlimitedGPT version: 

### Expected Behavior

Describe what you expected to happen when encountering the issue.

### Possible Solutions

If you have any ideas or suggestions for resolving the issue, please mention them here.

### Additional Context

Provide any additional information or context that may be helpful in understanding and resolving the issue. This can include:

- Any modifications made to the library or code.
- Any related information about the system or environment.
- Screenshots, if applicable, to visually illustrate the issue.

### Checklist

Before submitting the issue, please ensure that you have done the following:

- [x] I have reviewed the documentation before submitting this but report.
- [x] I have confirmed that I am running the latest version of UnlimitedGPT.
- [ ] I have verified that the issue is not caused by any modifications you made to the library or code.
- [ ] I have confirmed that the issue is caused by the library itself and not other dependencies used. [E.G headless mode not working because of undetected-chromedriver]

Thank you for taking the time to report this issue. Your contribution helps improve UnlimitedGPT for everyone!

**Comment by Sxvxgee** [comment]
Did you really just submit an issue without actually taking the time and adding description of it and answering the questions in the template? Next time please don't ignore them.

Anyhow, the headless parameter not working is not caused by UnlimitedGPT, but rather by undetected-chromedriver, so make an issue in their repository.
